### ISSUE TITLE
Release notes from pull requests

### ISSUE THREAD

**Issue by lsbardel** [quantmind/pulsar-agile#5]
The idea is to create the release notes from pull requests.
The search string for the github api should be:

```
/repos/:owner/:repo/pulls?state=closed&sort=updated&direction=desc
```

And pick only the pull requests after a given date (last release)

For example:

https://api.github.com/repos/quantmind/pulsar/pulls?state=closed&sort=updated&direction=desc

In this way we also get the pull request url and user url.

We should also scan commits between these releases and if a commit has a comment marked as #release-note, that comment should also be included.

**Comment by svetlyak40wt** [comment]
Luka, hi!

There are many tools to build changelog from commit-messages or github's closed pull-requests. Take a look at the list I'm have here: https://allmychanges.com/help/changelog-generators/

**Comment by lsbardel** [comment]
Thanks for that!
I will have a look and hopefully find some inspiration for a python implementation.
